const sourceFiles = {
  outline: "KHUNG HOANG KINH TE_1A_KTVM_L02.docx",
  chartBook: "Thong tin cac bang va slide.docx",
};

const charts = {
  exportsTrend: {
    type: "line",
    title: "Xuat khau Viet Nam 2020-2023",
    caption: "2023 la nam dau tien kim ngach xuat khau giam sau chuoi tang lien tiep.",
    note: "Du lieu lay truc tiep tu file so lieu; nam 2023 duoc to nhan de the hien muc giam 4,4% so voi 2022.",
    data: {
      labels: ["2020", "2021", "2022", "2023"],
      datasets: [{ label: "Ty USD", data: [281.5, 336.3, 371.9, 355.5] }],
    },
    options: { tension: 0.35, fill: false, yTitle: "Ty USD" },
  },
  laborImpact: {
    type: "doughnut",
    title: "Lao dong bi anh huong 5T/2023",
    caption: "Khoang 510.000 lao dong bi anh huong viec lam, trong do 280.000 nguoi mat viec hoan toan.",
    note: "File so lieu ghi ro 280.000 mat viec va khoang 230.000 bi anh huong khac; bieu do gom thanh 2 phan de de thuyet trinh.",
    data: {
      labels: ["Mat viec hoan toan", "Giam gio lam / anh huong khac"],
      datasets: [{ label: "Nguoi", data: [280000, 230000] }],
    },
  },
  sectorImpact: {
    type: "bar",
    title: "Lao dong det may va dien tu Q2/2023",
    caption: "Det may chiu cu soc lao dong nang hon dien tu trong giai doan don hang sut giam.",
    note: "Nguon chi cung cap muc giam so voi Q1/2023, nen bieu do the hien chenh lech am tuyet doi.",
    data: {
      labels: ["Det may", "Dien tu"],
      datasets: [{ label: "Giam lao dong so voi Q1/2023", data: [-142500, -30200] }],
    },
    options: { yTitle: "Nguoi" },
  },
  fdiShare: {
    type: "pie",
    title: "Co cau xuat khau 2024",
    caption: "Khu vuc FDI chiem hon 2/3 kim ngach xuat khau, lam Viet Nam nhay voi quyet dinh cua doanh nghiep nuoc ngoai.",
    note: "So lieu lay truc tiep tu file so lieu: FDI 71,7% va khu vuc trong nuoc 28,3%.",
    data: {
      labels: ["FDI", "Trong nuoc"],
      datasets: [{ label: "Ty trong", data: [71.7, 28.3] }],
    },
  },
  realEstateCredit: {
    type: "bar",
    title: "Tin dung BDS 2019-2022",
    caption: "Ba nam dau tang manh quanh 26%/nam; 2022 duoc danh dau la giai doan bat dau siet va dao chieu ky vong.",
    note: "Tai lieu chi neu chinh xac muc +26% cho 2019-2021. Nam 2022 khong co so phan tram cu the, nen duoc bieu dien bang nhan 'bat dau siet' thay vi cot so lieu.",
    data: {
      labels: ["2019", "2020", "2021", "2022"],
      datasets: [{ label: "% tang truong duoc neu ro trong tai lieu", data: [26, 26, 26, null] }],
    },
    options: { yTitle: "% tang truong" },
  },
  apartmentPrice: {
    type: "line",
    title: "Gia can ho so cap Ha Noi 2022-2024",
    caption: "Gia so cap tang lien tuc ngay ca khi thanh khoan thi truong yeu, phan anh ky vong va herd behavior.",
    note: "Moc 2022 va 2023 duoc lay theo khoang gia trung binh trong tai lieu va chuan hoa ve mot diem giua de ve line: 37 va 47 trieu dong/m2; 2024 dung muc 64 trieu dong/m2 theo vi du chuan hoa trong file so lieu.",
    data: {
      labels: ["2022", "2023", "2024"],
      datasets: [{ label: "Trieu dong/m2", data: [37, 47, 64] }],
    },
    options: { tension: 0.3, yTitle: "Trieu dong/m2" },
  },
  bondMaturityShare: {
    type: "doughnut",
    title: "Co cau dao han trai phieu 2025",
    caption: "BDS chiem hon mot nua khoi luong dao han, nen ap luc refinance don vao khu vuc nay.",
    note: "Nguon chi neu 'BDS chiem hon 50%'. Bieu do chuan hoa thanh 51/49 de truc quan hoa logic 'hon mot nua', khong phai ty le chinh xac cuoi cung.",
    data: {
      labels: ["BDS (>50%)", "Cac nganh khac (<50%)"],
      datasets: [{ label: "Ty trong chuan hoa", data: [51, 49] }],
    },
  },
  bondStress: {
    type: "bar",
    title: "Ap luc trai phieu BDS 2024-2025",
    caption: "Khung hoang khong den tu mot con so rieng le ma tu ba ap luc chong len nhau.",
    note: "Ba dai luong co don vi khac nhau nen duoc hien thi cung mot bieu do dang chi bao, moi cot di kem nhan don vi trong panel so lieu.",
    data: {
      labels: ["To chuc cham nghia vu", "Du no cham nghia vu", "Dao han 2025"],
      datasets: [{ label: "Gia tri truc quan hoa", data: [90, 190, 210] }],
    },
    options: { yTitle: "Gia tri quy uoc de so sanh tren cung mat phang" },
  },
  svbMetrics: {
    type: "bar",
    title: "SVB 2023 - cac chi so chinh",
    caption: "Lo HTM, tien gui khong bao hiem va quy mo rut tien cung chi vao mot bang can doi de vo khi niem tin dao chieu.",
    note: "Bieu do dung cac so tuyet doi theo tai lieu: 212 ty USD tai san, 15,1 ty USD lo HTM, 94% tien gui khong bao hiem va 42 ty USD bi rut trong 8 gio.",
    data: {
      labels: ["Tong tai san", "Lo HTM", "Tien gui rut 8 gio", "Ty le tien gui khong BH"],
      datasets: [{ label: "Gia tri goc / %", data: [212, 15.1, 42, 94] }],
    },
    options: { yTitle: "Ty USD / %" },
  },
  usHousing: {
    type: "line",
    title: "Gia nha My giai doan bong bong 2000-2009",
    caption: "Bong bong duoc tich luy nhieu nam truoc khi vo, nen lai suat thap chi la dieu kien khuech dai.",
    note: "Cac moc du lieu lay tu file so lieu: 2000, 2005, 2006 va 2009. Duong noi the hien xu huong chu khong noi suy them nam moi.",
    data: {
      labels: ["2000", "2005", "2006", "2009"],
      datasets: [{ label: "Nghin USD/can", data: [156, 240, 257.4, 180] }],
    },
    options: { tension: 0.25, yTitle: "Nghin USD/can" },
  },
  fedVsHousing: {
    type: "mixed",
    title: "FED rate la dieu kien khuech dai",
    caption: "Lai suat re giup don bay phinh to hon, nhung hanh vi cho vay va chung khoan hoa moi la noi rui ro duoc tao ra.",
    note: "Truc trai la lai suat FED o cac moc duoc neu trong tai lieu; truc phai la gia nha My tai cac moc chinh. Cac nam trong duoc bo qua thay vi tu dien them.",
    data: {
      labels: ["2000", "2003-2004", "2005", "2006-2007", "2008", "2009"],
      datasets: [
        { label: "FED rate (%)", type: "line", yAxisID: "y", data: [6, 1, null, 5.25, 0, null] },
        { label: "Gia nha (nghin USD/can)", type: "bar", yAxisID: "y1", data: [156, null, 240, 257.4, null, 180] },
      ],
    },
    options: { dualAxis: true, yTitle: "FED rate (%)", y1Title: "Nghin USD/can" },
  },
};

export const siteData = {
  metadata: {
    title: "Khung hoang Kinh te, Phe 1A",
    subtitle: "Market Failure & Long Tham cua Thi Truong",
    group: "Nhom 4",
    className: "L02",
    quote: "Khung hoang khong no tu thong cao chinh sach. No no tu bang can doi tu nhan da chat day rui ro.",
    footerNote: "Version 1 tap trung vao flow thuyet trinh, du lieu va nguon. Phan bien va cross-examination khong tach section rieng.",
  },
  glossary: {
    "Asymmetric Information": "Thong tin bat can xung: ben phat hanh hoac ban san pham tai chinh biet nhieu hon nguoi mua, lam rui ro bi che giau.",
    "Principal-Agent Problem": "Van de uy thac - dai ly: nguoi chot giao dich huong loi ngan han nhung khong ganh du hau qua dai han.",
    "Moral Hazard": "Rui ro dao duc: khi chu the tin rang neu do vo se duoc cuu hoac gia han, ho se chap nhan rui ro cao hon.",
    "Herd Behavior": "Tam ly bay dan: quyet dinh mua hoac ban theo dam dong thay vi theo gia tri thuc.",
    "Leverage Cycle": "Vong xoay don bay: gia tai san tang lam tai san the chap trong an toan hon, keo them von vay va day gia len tiep.",
    "Liquidity/Maturity Mismatch": "Lech ky han: dung nguon von ngan han de tai tro tai san dai han, dan toi ap luc thanh khoan khi von ngan khong dao duoc.",
    "Negative Externality": "Ngoai tac tieu cuc: mot chu the toi uu loi ich rieng nhung day chi phi sang nguoi lao dong, nha cung ung hoac toan xa hoi.",
    Contagion: "Lay lan: mot mat xich suy yeu lam niem tin lan xau sang toan he thong, ke ca voi ben khong truc tiep gay loi.",
  },
  charts,
  sections: [
    {
      id: "cover",
      navLabel: "01 Cover",
      eyebrow: "Chu de 1",
      title: "Khung hoang Kinh te",
      subtitle: "Phe 1A dat cau hoi ve noi rui ro duoc tich luy truoc cu soc.",
      keyMessage: "Chung toi khong phu nhan vai tro cua chinh sach. Luan diem cot loi la: bang can doi tu nhan moi la noi fragility duoc tao ra truoc khi cu soc toi.",
      intro: [
        "Microsite nay dung lai flow thuyet trinh hoc thuat theo phong cach trinh chieu toan man hinh.",
        "Toan bo so lieu va lap luan trong version 1 duoc lay tu bo tai lieu nhom da chuan bi trong thread hien tai.",
      ],
      keyPoints: [
        "Chu de tranh luan: dau la nguyen nhan goc cua khung hoang kinh te.",
        "Hai file nguon chinh duoc tach vai tro ro rang: mot cho lap luan, mot cho du lieu va logic chart.",
        "Website duoc thiet ke image-ready de co the thay anh that vao sau ma khong phai sua layout lon.",
      ],
      dataCards: [
        { label: "Nhom / lop", value: "Nhom 4 - L02", note: "Co the sua nhanh trong data.js." },
        { label: "Tong chu dao", value: "Navy - White - Gold", note: "Toi uu cho man chieu va GitHub Pages." },
        { label: "Version 1", value: "12 section", note: "Khong tach rieng rebuttal hay cross-examination." },
      ],
      visuals: [{ type: "quote", label: "Tuyen bo mo dau", quote: "Khung hoang khong no tu thong cao chinh sach. No no tu bang can doi tu nhan da chat day rui ro." }],
      media: {
        label: "Hero visual / background image",
        path: "assets/images/cover-hero.jpg",
        alt: "Hero visual cho section cover",
        hint: "Chua san khu vuc anh nen hoac visual tong hop cho opening slide.",
      },
      sources: [{ name: sourceFiles.outline, uses: "Tieu de, framing, quote mo dau, dinh nghia tran dau." }],
    },
    {
      id: "hook",
      navLabel: "02 Hook",
      eyebrow: "Case mo dau",
      title: "Chi Hoa va cu soc don hang",
      subtitle: "Mot email cat don hang tu ben ngoai co the di thang vao bang luong cua cong nhan Viet Nam.",
      keyMessage: "Diem nhan cua phan mo dau khong chi la con so 280.000, ma la co che truyen cu soc tu thi truong the gioi vao khu vuc thuc trong nuoc.",
      intro: [
        "Thang 4/2023, case chi Hoa duoc dung de keo tranh luan ve he qua rat cu the cua mot cau truc thi truong mong manh.",
        "Website dung panel du lieu gon de nguoi thuyet trinh bat so lieu dung luc thay vi nhoi chu len mot man hinh.",
      ],
      keyPoints: [
        "280.000 nguoi mat viec trong 5 thang dau 2023.",
        "Khoang 510.000 lao dong bi anh huong viec lam theo Bo LDTBXH.",
        "Quyet dinh tu buyer quoc te co the lan sang nha may Viet Nam rat nhanh khi nen kinh te phu thuoc don hang.",
      ],
      dataCards: [
        { label: "Mat viec hoan toan", value: "280.000 nguoi", note: "Tuong duong quy mo dan so mot thanh pho tinh ly nhu Vinh Long." },
        { label: "Tong bi anh huong", value: "~510.000 nguoi", note: "Bao gom mat viec va giam gio lam trong 5 thang dau 2023." },
        { label: "Co che truyen soc", value: "Don hang -> nha may -> lao dong", note: "Di tu quyet dinh thi truong sang khu vuc thuc." },
      ],
      visuals: [{ type: "chart", chartId: "laborImpact", label: "Lao dong bi anh huong" }],
      media: {
        label: "Anh cong nhan / nha may",
        path: "assets/images/hook-worker.jpg",
        alt: "Anh minh hoa cong nhan va nha may",
        hint: "Layout goi y: text trai, anh lon phai.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Case chi Hoa, framing 'email tu ben ngoai den bang luong trong nuoc'." },
        { name: sourceFiles.chartBook, uses: "280.000 mat viec, ~510.000 bi anh huong, logic so sanh va hinh tuong hoa." },
      ],
    },
    {
      id: "framework",
      navLabel: "03 Framework",
      eyebrow: "4 tang nhan qua",
      title: "Root Cause, Trigger, Amplifier, Response",
      subtitle: "Framework nay giup tach noi rui ro duoc tao ra khoi noi rui ro bi lam lo hoac bi xu ly.",
      keyMessage: "Root Cause phai noi bat nhat: do la noi rui ro tich luy truoc cu soc.",
      intro: ["Tai lieu lap luan nhan rat manh viec phan biet 4 tang nhan qua de tranh danh trao nguyen nhan goc voi chinh sach hay phan ung hau khung hoang."],
      keyPoints: [
        "Root Cause: noi rui ro tich luy truoc cu soc.",
        "Trigger: cu hich lam lo vet nut.",
        "Amplifier: co che khien cu soc lan rong.",
        "Response: hanh dong don hau qua cua chinh phu hoac NHTW.",
      ],
      dataCards: [
        { label: "Tang 1", value: "Root Cause", note: "THI TRUONG TU NHAN duoc nhan noi bat trong flow 1A." },
        { label: "Tang 2", value: "Trigger", note: "Co the la policy hoac cu soc ngoai sinh." },
        { label: "Tang 3-4", value: "Amplifier / Response", note: "Giai thich vi sao khung hoang lan rong va ai xu ly hau qua." },
      ],
      visuals: [{
        type: "framework",
        label: "So do 4 tang",
        items: [
          { title: "Root Cause", subtitle: "Noi rui ro tich luy truoc cu soc", emphasis: true },
          { title: "Trigger", subtitle: "Cu hich lam lo vet nut" },
          { title: "Amplifier", subtitle: "Ban thao, lay lan, margin call" },
          { title: "Response", subtitle: "Cuu tro, tai co cau, giam lai suat" },
        ],
      }],
      media: {
        label: "Diagram area",
        path: "assets/images/framework-diagram.jpg",
        alt: "Khung so do 4 tang nhan qua",
        hint: "Section nay uu tien diagram hon anh that.",
      },
      sources: [{ name: sourceFiles.outline, uses: "Dinh nghia tung tang va vai tro cua Root Cause." }],
    },
    {
      id: "mechanism-leverage",
      navLabel: "04 Co che 1",
      eyebrow: "Leverage Cycle",
      title: "Vong xoay don bay",
      subtitle: "Gia tai san tang lam tai san the chap trong an toan hon, keo them von vay va nuoi chinh vong xoay do.",
      keyMessage: "Co che nay khong dang so nhat o luc di len, ma o luc dao chieu: khi tai san giam gia, cung vong lap chay nguoc lai nhanh va tan khoc hon.",
      intro: [
        "Vi du Viet Nam duoc dung trong tai lieu la tin dung BDS tang manh giai doan 2019-2021.",
        "Nam 2022 la diem doi pha ky vong khi thi truong bat dau bi siet va fragility lo ro hon.",
      ],
      keyPoints: [
        "Tin dung BDS tang khoang 26%/nam giai doan 2019-2021.",
        "Lai suat thap hau Covid giup don bay phinh len nhanh hon.",
        "2022 la moc bat dau dao chieu ky vong va rui ro refinance.",
      ],
      dataCards: [
        { label: "2019-2021", value: "+26%/nam", note: "Con so duoc nhac truc tiep trong tai lieu so lieu." },
        { label: "He qua", value: "Don bay gap doi sau 3 nam", note: "Theo logic X x (1,26)^3 gan bang 2X." },
        { label: "Mau chot", value: "Dao chieu nhanh", note: "Khi ky vong giam, co che don bay khuech dai pha di xuong." },
      ],
      visuals: [{ type: "chart", chartId: "realEstateCredit", label: "Chart tin dung BDS" }],
      media: {
        label: "Anh can ho / du an",
        path: "assets/images/hanoi-apartment.jpg",
        alt: "Anh minh hoa thi truong bat dong san",
        hint: "Co the thay bang anh du an, skyline hoac phoi canh BDS.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Giai thich co che Leverage Cycle va y nghia khi dao chieu." },
        { name: sourceFiles.chartBook, uses: "Muc tang 26%/nam va ghi chu cach tinh gap doi don bay sau 3 nam." },
      ],
    },
    {
      id: "mechanism-mismatch",
      navLabel: "05 Co che 2",
      eyebrow: "Liquidity / Maturity Mismatch",
      title: "Lech ky han",
      subtitle: "Vay ngan de tai tro tai san dai khien he thong song nho kha nang dao von lien tuc.",
      keyMessage: "Khi dong von ngan khong quay tiep, tai san dai han khong the ban kip de tra no va fragility lo ra ngay.",
      intro: ["Case Viet Nam trong tai lieu nhan rat ro: trai phieu doanh nghiep 2-3 nam dang phai ganh nhung du an can 5-10 nam de hoan von."],
      keyPoints: [
        "Doanh nghiep BDS dung TP 2-3 nam cho du an 5-10 nam.",
        "Cuoi 2024 co hon 90 to chuc cham nghia vu.",
        "Du no cham nghia vu khoang 190.000 ty dong.",
      ],
      dataCards: [
        { label: "Ky han trai phieu", value: "2-3 nam", note: "Nguon von ngan, can dao tiep neu du an chua co dong tien." },
        { label: "Vong doi du an", value: "5-10 nam", note: "Khoang cach ky han chinh la phan rui ro." },
        { label: "Ap luc cuoi 2024", value: "90+ / 190.000 ty", note: "So to chuc cham nghia vu va quy mo du no duoc neu truc tiep trong file so lieu." },
      ],
      visuals: [{
        type: "timeline-lanes",
        label: "Timeline lech ky han",
        lanes: [
          { title: "Trai phieu / von ngan han", span: "2-3 nam", detail: "Huy dong nhanh, dao han som, phu thuoc refinance." },
          { title: "Du an BDS / tai san dai han", span: "5-10 nam", detail: "Hoan von cham, de nghen vi phap ly va thanh khoan." },
        ],
        gapLabel: "Khoang lech ky han = vung rui ro thanh khoan",
      }],
      media: {
        label: "Anh ho so du an / trai phieu",
        path: "assets/images/bond-project-gap.jpg",
        alt: "Anh minh hoa trai phieu va du an dai han",
        hint: "Neu chua co anh, placeholder nay van giu ty le va vi tri cho layout 2 cot.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Dinh nghia mismatch va ly do fragility nam o cau truc funding." },
        { name: sourceFiles.chartBook, uses: "Ky han 2-3 nam vs 5-10 nam, 90+ to chuc, ~190.000 ty dong." },
      ],
    },
    {
      id: "mechanism-herd",
      navLabel: "06 Co che 3",
      eyebrow: "Herd Behavior",
      title: "Tam ly bay dan",
      subtitle: "Gia tang keo them nguoi mua moi, con tin xau co the kich hoat mot pha thao chay cuc nhanh.",
      keyMessage: "Herd behavior vua xuat hien o thi truong tai san nhu can ho Ha Noi, vua xuat hien o bank run so hoa nhu SVB.",
      intro: ["Tai lieu so sanh rat ro hai hinh thuc cua cung mot co che: FOMO tren thi truong can ho va panic run tren tien gui ngan hang."],
      keyPoints: [
        "Gia can ho so cap Ha Noi tang manh trong 2024.",
        "SVB chung kien 42 ty USD bi rut chi trong 8 gio.",
        "Niem tin va hanh vi dam dong co the tu khuech dai ma khong can thay doi lon ve fundamentals trong ngan han.",
      ],
      dataCards: [
        { label: "Ha Noi 2024", value: "+35-40%", note: "Tang gia so cap du thanh khoan thi truong yeu." },
        { label: "SVB 09/03/2023", value: "42 ty USD / 8 gio", note: "Bank run so hoa o toc do chua tung co tien le." },
        { label: "So sanh", value: "FOMO vs Panic", note: "Cung la hanh vi bay dan, khac nhau o huong chuyen dong cua niem tin." },
      ],
      visuals: [
        { type: "chart", chartId: "apartmentPrice", label: "Gia can ho Ha Noi" },
        {
          type: "comparison",
          label: "So sanh Viet Nam va SVB",
          items: [
            { title: "Ha Noi 2024", detail: "Ky vong gia tang tiep keo nguoi mua vao du thanh khoan khong khoe." },
            { title: "SVB 2023", detail: "Tin xau tren mang xa hoi khien nguoi gui tien rut dong loat trong vai gio." },
          ],
        },
      ],
      media: {
        label: "Anh can ho Ha Noi",
        path: "assets/images/hanoi-apartment.jpg",
        alt: "Anh minh hoa can ho Ha Noi",
        hint: "Anh that co the la skyline, block can ho hoac anh thi truong so cap.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Dinh nghia Herd Behavior va doi chieu voi SVB." },
        { name: sourceFiles.chartBook, uses: "Gia can ho 2022-2024, logic tang 35-40%, case SVB bank run." },
      ],
    },
    {
      id: "real-estate-vn",
      navLabel: "07 BDS Viet Nam",
      eyebrow: "Vietnam 2021-2025",
      title: "BDS Viet Nam: ba co che hoat dong cung nhau",
      subtitle: "Don bay, lech ky han va herd behavior khong tach roi, ma don vao cung mot cau truc bang can doi.",
      keyMessage: "190.000 ty dong cham nghia vu khong xuat hien trong mot thang; no la phan rui ro tich luy tu giai doan bung no truoc do.",
      intro: ["Section nay gom 3 co che thanh mot case tich hop de nguoi thuyet trinh co the noi mach nguyen nhan thay vi ke tung manh roi rac."],
      keyPoints: [
        "Tin dung BDS phinh nhanh giai doan 2019-2021.",
        "Mo hinh refinance tao ra dependency vao phat hanh moi.",
        "Khi niem tin giam, ca thanh khoan lan chi phi von cung xau di.",
      ],
      dataCards: [
        { label: "Cham nghia vu", value: "90+ to chuc", note: "Chu yeu la to chuc phat hanh gan voi BDS theo tai lieu so lieu." },
        { label: "Du no cham nghia vu", value: "~190.000 ty dong", note: "Tich luy tu cac dot phat hanh 2020-2022." },
        { label: "Dao han 2025", value: ">200.000 ty dong", note: "BDS chiem hon mot nua ap luc dao han." },
      ],
      visuals: [
        { type: "chart", chartId: "bondMaturityShare", label: "Pie dao han 2025" },
        { type: "chart", chartId: "bondStress", label: "Bar ap luc BDS" },
      ],
      media: {
        label: "Anh du an BDS / trai phieu",
        path: "assets/images/real-estate-bonds.jpg",
        alt: "Anh minh hoa trai phieu va du an bat dong san",
        hint: "Uu tien anh du an dang xay hoac visual ve trai phieu doanh nghiep.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Logic 3 co che cung hoat dong trong case BDS Viet Nam." },
        { name: sourceFiles.chartBook, uses: "Ap luc dao han 2025, ty trong BDS hon 50%, so to chuc cham nghia vu, du no cham nghia vu." },
      ],
    },
    {
      id: "export-shock",
      navLabel: "08 Xuat khau",
      eyebrow: "External market shock",
      title: "Cu soc xuat khau va lao dong 2023",
      subtitle: "Cau ben ngoai yeu di truyen rat nhanh vao san luong, viec lam va ky vong trong nuoc.",
      keyMessage: "Dieu dang chu y khong chi la muc giam xuat khau, ma la do mo va ty trong FDI khien cu soc ben ngoai co suc nang dac biet voi Viet Nam.",
      intro: ["Day la section giau du lieu nhat vi can cho thay chuoi truyen dan cu the tu thi truong the gioi den nguoi lao dong trong nuoc."],
      keyPoints: [
        "Xuat khau ca nam 2023 giam con 355,5 ty USD.",
        "Det may va dien tu deu mat lao dong trong Q2/2023.",
        "FDI chiem 71,7% xuat khau nam 2024, lam Viet Nam nhay voi quyet dinh cua doanh nghiep nuoc ngoai.",
      ],
      dataCards: [
        { label: "Xuat khau 2023", value: "355,5 ty USD", note: "Giam 4,4% so voi 2022." },
        { label: "Do mo kinh te 2024", value: "~170% GDP", note: "XNK 786,29 ty USD so voi GDP khoang 469 ty USD." },
        { label: "FDI trong XK", value: "71,7%", note: "Hon 2/3 kim ngach xuat khau den tu khu vuc FDI." },
      ],
      visuals: [
        { type: "chart", chartId: "exportsTrend", label: "Line xuat khau" },
        { type: "chart", chartId: "laborImpact", label: "Chart lao dong" },
        { type: "chart", chartId: "sectorImpact", label: "Det may vs dien tu" },
        { type: "chart", chartId: "fdiShare", label: "FDI vs trong nuoc" },
      ],
      media: {
        label: "Anh nha may / day chuyen / xuat khau",
        path: "assets/images/export-factory.jpg",
        alt: "Anh minh hoa xuat khau va lao dong",
        hint: "Layout 2 cot: text + nhieu chart; anh co the dat o cot phu hoac header panel.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Logic truyen cu soc don hang quoc te vao lao dong Viet Nam." },
        { name: sourceFiles.chartBook, uses: "Xuat khau 2020-2023, 5T/2023, lao dong, det may, dien tu, do mo kinh te va ty trong FDI." },
      ],
    },
    {
      id: "red-sea",
      navLabel: "09 Bien Do",
      eyebrow: "Negative Externality",
      title: "Bien Do Q1/2024",
      subtitle: "Mot cu soc logistics ben ngoai boc lo cai gia cua chuoi cung ung toi uu qua mong vung dem.",
      keyMessage: "Day la ngoai tac tieu cuc vi loi ich toi uu chi phi cua mot so chu the duoc chuyen thanh chi phi giao van va thoi gian cua ca chuoi.",
      intro: ["Section nay khong can qua nhieu chu; visual route va hai cap before-after la du de nguoi thuyet trinh ke chuyen."],
      keyPoints: [
        "Luu luong qua Suez / Bab el-Mandeb giam khoang 50%.",
        "Chi phi container tuyen A - Au tang them 1.000-2.000 USD/container.",
        "Thoi gian van chuyen Viet Nam - EU tang them 10-14 ngay.",
      ],
      dataCards: [
        { label: "Luu luong qua Suez", value: "-50%", note: "So voi truoc xung dot theo World Bank / UNCTAD." },
        { label: "Chi phi container", value: "+1.000 den +2.000 USD", note: "Tuyen A - Au sau cu soc logistics." },
        { label: "Thoi gian van chuyen", value: "+10 den +14 ngay", note: "Do phai di vong qua Mui Hao Vong." },
      ],
      visuals: [
        {
          type: "route",
          label: "Tuyen Suez vs Mui Hao Vong",
          routes: [
            { title: "Truoc cu soc", detail: "Tuyen ngan qua Suez, chi phi thap hon, thoi gian on dinh hon." },
            { title: "Sau cu soc", detail: "Phai di vong qua Mui Hao Vong, chi phi va thoi gian cung tang." },
          ],
        },
        {
          type: "comparison",
          label: "Before - After",
          items: [
            { title: "Container A - Au", detail: "Tu khoang 1.000-1.500 USD len 2.000-3.500 USD/container." },
            { title: "VN -> EU", detail: "Tu khoang 30 ngay len 40-44 ngay van chuyen." },
          ],
        },
      ],
      media: {
        label: "Anh cang bien / container",
        path: "assets/images/red-sea-logistics.jpg",
        alt: "Anh minh hoa logistics Bien Do",
        hint: "Co the thay bang anh tau container, cang bien hoac route map that.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Giai thich tai sao day la negative externality trong cau truc chuoi cung ung." },
        { name: sourceFiles.chartBook, uses: "Luu luong Suez, chi phi container va thoi gian van chuyen tang them." },
      ],
    },
    {
      id: "svb",
      navLabel: "10 SVB",
      eyebrow: "Case study 2023",
      title: "SVB 2023 - lech ky han so hoa",
      subtitle: "Mot bang can doi chua duration mismatch va funding tap trung co the sup trong vai gio.",
      keyMessage: "Lai suat tang la stress test; SVB vo vi cau truc bang can doi yeu, khong phai vi moi ngan hang deu tat yeu chet duoi cung mot muc lai suat.",
      intro: ["SVB duoc dung nhu case quoc te gan, manh va kho tranh cai: so lieu moi, ro, va gan truc tiep voi ca mismatch lan herd behavior."],
      keyPoints: [
        "Tong tai san nam 2022 khoang 212 ty USD.",
        "Lo chua thuc hien HTM 15,1 ty USD vao cuoi 2022.",
        "Khoang 94% tien gui khong duoc bao hiem va 42 ty USD bi rut trong 8 gio.",
      ],
      dataCards: [
        { label: "Tong tai san", value: "212 ty USD", note: "Ngan hang lon thu 16 cua My tai thoi diem do." },
        { label: "Lo HTM", value: "15,1 ty USD", note: "Vuot toan bo von chu so huu cot loi theo tai lieu." },
        { label: "Tien gui khong bao hiem", value: "~94%", note: "Muc cuc cao so voi mat bang nganh." },
      ],
      visuals: [
        { type: "chart", chartId: "svbMetrics", label: "Bar chi so chinh" },
        {
          type: "timeline",
          label: "Timeline 8 gio bank run",
          steps: [
            "Tin xau lan nhanh trong cong dong startup va VC.",
            "Khach hang gui lenh rut o toc do chua tung co.",
            "42 ty USD roi khoi SVB trong 8 gio giao dich.",
            "Stress test ve niem tin bien thanh khung hoang thanh khoan thuc su.",
          ],
        },
      ],
      media: {
        label: "Anh SVB / bank run",
        path: "assets/images/svb-bank.jpg",
        alt: "Anh minh hoa SVB bank run",
        hint: "Co the thay bang anh tru so SVB, queue khach hang hoac do hoa tin tuc.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Luan diem rang rate hike la stress test, khong phai root cause duy nhat." },
        { name: sourceFiles.chartBook, uses: "212 ty USD tai san, 15,1 ty USD lo HTM, 94% tien gui khong bao hiem, 42 ty USD rut trong 8 gio." },
      ],
    },
    {
      id: "crisis-2008",
      navLabel: "11 Khung hoang 2008",
      eyebrow: "Global leverage spiral",
      title: "Khung hoang 2008",
      subtitle: "Bong bong nha dat, chung khoan hoa no xau va incentive lech cung tich luy nhieu nam truoc khi sup.",
      keyMessage: "FED rate thap la dieu kien khuech dai, nhung liar loans, securitization va xep hang tin nhiem meo mo moi la noi rui ro duoc tao ra.",
      intro: ["Section nay chot tinh lich su cua lap luan: khung hoang khong no vi mot cu nhan nham chinh sach, ma vi thi truong tin rang rui ro da bien mat."],
      keyPoints: [
        "Gia nha My tang tu khoang 156.000 USD nam 2000 len 257.400 USD nam 2006.",
        "Lehman Brothers pha san ngay 15/09/2008 voi khoang 639 ty USD tai san.",
        "Lai suat FED thap giup fuel cho chu ky don bay nhung khong tu viet ra liar loans hay tao ra MBS doc hai.",
      ],
      dataCards: [
        { label: "Dinh gia nha", value: "257.400 USD", note: "Moc dinh giua 2006 duoc neu trong file so lieu." },
        { label: "Lehman Brothers", value: "639 ty USD tai san", note: "Vu pha san lon nhat lich su My tai thoi diem do." },
        { label: "FED 2003-2004", value: "1%", note: "Dieu kien khuech dai chu khong phai nguyen nhan goc." },
      ],
      visuals: [
        { type: "chart", chartId: "usHousing", label: "Line gia nha My" },
        { type: "chart", chartId: "fedVsHousing", label: "FED vs gia nha" },
      ],
      media: {
        label: "Anh Lehman Brothers / 2008 crisis",
        path: "assets/images/lehman-2008.jpg",
        alt: "Anh minh hoa khung hoang 2008",
        hint: "Anh phu hop la Lehman, pho Wall hoac trang bao 2008.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Narrative ve liar loans, CDO/MBS, rating agencies va cau ket luan ve root cause." },
        { name: sourceFiles.chartBook, uses: "Cac moc gia nha My, tai san Lehman, FED rate va note Case-Shiller." },
      ],
    },
    {
      id: "conclusion",
      navLabel: "12 Ket luan",
      eyebrow: "Closing",
      title: "Ba co che tu nhan la thuoc no tich luy, chinh sach la tia lua",
      subtitle: "BDS Viet Nam, lao dong xuat khau, SVB va 2008 cung ke mot cau chuyen ve noi fragility duoc tich luy.",
      keyMessage: "Quay lai case chi Hoa: nguoi lao dong khong mat viec vi mot thong cao don le, ma vi ca chuoi khong co vung dem khi cu soc toi.",
      intro: ["Closing duoc thiet ke it chu hon cac section giua de phu hop nhip ket bai tren laptop hoac man hinh chieu."],
      keyPoints: [
        "Leverage, mismatch va herd behavior la ba co che lap di lap lai.",
        "Policy co the lam cu soc manh hon hoac yeu di, nhung khong phai noi rui ro duoc tich luy tu dau.",
        "Case chi Hoa giup keo moi khai niem tai chinh tro ve tac dong rat thuc len nguoi lao dong.",
      ],
      dataCards: [
        { label: "Ba co che", value: "Leverage - Mismatch - Herd", note: "Soi chi do xuyen suot tat ca case." },
        { label: "Chinh sach", value: "Tia lua / stress test", note: "Khong bi phu nhan, nhung khong phai noi root cause nam san." },
        { label: "Case goi lai", value: "Chi Hoa", note: "Diem neo de ket tu khai niem lon ve lai he qua xa hoi." },
      ],
      visuals: [{ type: "quote", label: "Quote ket", quote: "Khung hoang khong no tu thong cao chinh sach. No no tu bang can doi tu nhan da chat day rui ro." }],
      media: {
        label: "Visual tong hop / quote-focused layout",
        path: "assets/images/final-synthesis.jpg",
        alt: "Visual tong hop cho section ket luan",
        hint: "Co the thay bang anh timeline tong hop hoac giu placeholder de nhan quote.",
      },
      sources: [
        { name: sourceFiles.outline, uses: "Cau ket, logic 'ba co che = thuoc no, chinh sach = tia lua'." },
        { name: sourceFiles.chartBook, uses: "Nguon tong hop cua cac con so duoc goi lai trong closing." },
      ],
    },
  ],
};
